services:
  db:
    image: mysql:9
    container_name: db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - cdapp-network
    ports:
      - 6006:3306

  app:
    depends_on:
      - db
    build: .
    restart: on-failure
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://app_db:3306/$DB_DATABASE
      - SPRING_DATASOURCE_USERNAME=$DB_USER
      - SPRING_DATASOURCE_PASSWORD=$DB_PASSWORD
    networks:
      - cdapp-network
    ports:
      - 8888:8080
    links:
      - db:app_db

networks:
  cdapp-network:
    driver: bridge